MERGE INTO STATUS KEY (id) VALUES (1, 'WAITING');
MERGE INTO STATUS KEY (id) VALUES (2, 'APPROVED');
MERGE INTO STATUS KEY (id) VALUES (3, 'REJECTED');
MERGE INTO STATUS KEY (id) VALUES (4, 'CANCELED');
